backend:
  name: github
  repo: Masturberen/JOUW_REPO
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: false
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "music"
    label: "Music"
    folder: "content/music"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
backend:
  name: github
  repo: Masturberen/Kopfsorge CMS
  branch: main
  client_id: Iv23lifbpIgeTnTUqsiz

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://blog.honingpot.online

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
