backend:
  name: github
  repo: Masturberen/kopfsorge
  branch: main
  base_url: https://github.com
  auth_endpoint: /login/oauth/authorize
  app_id: Iv23lifbpIgeTnTUqsiz

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "music"
    label: "Music / Mixtapes"
    folder: "content/music"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Audio file", name: "audio", widget: "file", media_library: { allow_multiple: false } }
      - { label: "Description", name: "body", widget: "markdown" }
